### ISSUE TITLE
LB Mod Installer: BAC.xml Binary false error

### ISSUE THREAD

**Issue by StardustZfighter** [LazyBone152/XV2-Tools#14]
Newest version of LB Mod Installer cannot install bac.xml files. it says Failed at BAC Install Phase. Type: Binary is not possible for BAC files. must use XML. However the file inside the installer is already in bac.xml (turned to xml by the xmltool within the installer). However the older versions of the mod installer seems to work fine

**Comment by LazyBone152** [comment]
Confirmed and fixed.
