### ISSUE TITLE
LB Mod Installer: Super Soul Name Mix

### ISSUE THREAD

**Issue by StardustZfighter** [LazyBone152/XV2-Tools#18]
Whenever new custom super souls are installed if they have their full msgscomponents (name, info, LimitBurst, LimitBurstBattle) their names get mixed up with other custom super souls despite having different effects

**Comment by LazyBone152** [comment]
I cant reproduce this bug. I tried with 3 custom souls with full names, info and LB names and all install correctly.

Do you have a specific mod that has this bug that I can test?

**Comment by StardustZfighter** [comment]
It seems that there was an issue with another mod that got fixed

**Comment by LazyBone152** [comment]
Ok so it wasn't an installer bug?

**Comment by StardustZfighter** [comment]
no
