### ISSUE TITLE
EEPK Organiser features not working. 

### ISSUE THREAD

**Issue by Erichsen-Xero** [LazyBone152/XV2-Tools#21]
Some of the features in the EEPK org just flat out don't work. 

1. The ability to remove particle/ child particle effect subentries from an EMP's `Edit` panel often does nothing. The only viable fix is removing the concerned subentries manually in XML. 

2. The `Remove Color Animations` option in the `PBIND` menu also often does nothing at all. Only alternative is removing the Color Animations for each EMP in the `Edit` panel one by one.

**Comment by StardustZfighter** [comment]
The first bug is actually visual. as you re open the emp, the children are added or removed. so it's actually a visual bug.

**Comment by Erichsen-Xero** [comment]
> The first bug is actually visual. as you re open the emp, the children are added or removed. so it's actually a visual bug.

I have verified the issue through XML and I haven't been able to confirm that it's solely visual, the entries removed can still be found in the XMLised EMP. 
Even if it is, then the problem remaining is that it creates a sense of dissonance and is quite counterintuitive to the motive of editing things using a Graphical UI.

**Comment by LazyBone152** [comment]
From my tests 1 is just visual. You can verify it by exiting out of the EMP Editor and then reopening it. The deleted entry should be gone.

The problem also extends to creating new particle effects as children and pasting. Basically any action that creates or deletes a particle effect at anything other than the root level causes it.

**Comment by Erichsen-Xero** [comment]
> The problem also extends to creating new particle effects as children and pasting. Basically any action that creates or deletes a particle effect at anything other than the root level causes it.

Got it, I'll recheck it in that case. Is this issue fixable in a prospective update btw?

**Comment by LazyBone152** [comment]
I have already fixed it. I'm not entirely sure why it wasn't updating correctly in the first place but fixing it is as simple as forcing a refresh anytime an entry is added or removed.

As for 2, I cant reproduce this at all. Have you got any example when this happens?

**Comment by Erichsen-Xero** [comment]
> As for 2, I cant reproduce this at all. Have you got any example when this happens?

The issue has recurrently happened to me in the recent past but I don't really know how exactly to reproduce it consistently. It just happens at random to the best of my recollection.

**Comment by LazyBone152** [comment]
Well the relevant code is fairly simple and I just can't see any issue with it that would cause such an issue. The only case where color anims aren't removed are if its alpha, which is expected. 

Since I cant reproduce this issue I think I'll just release an update with the fix for the other issue. Maybe I could add some feedback to let the user know how many anims were (or not) removed.
