### ISSUE TITLE
XV2 XML Serialiser flags "AwokenSkill" declarations for the EEPK Skill Type in Effect Subentries for BSAs as "SuperSkill"

### ISSUE THREAD

**Issue by Erichsen-Xero** [LazyBone152/XV2-Tools#22]
Effect sub-entries in the BSA that should signify `AwokenSkill` entries are instead denominated as `SuperSkill` Type EEPKs.

**Comment by LazyBone152** [comment]
It looks normal to me. See here:
<img width="164" alt="bsa" src="https://user-images.githubusercontent.com/60512194/143485190-6c12ae17-34b7-4214-b271-67497f818805.png">

For reference, here is bac:
<img width="140" alt="bac" src="https://user-images.githubusercontent.com/60512194/143485223-f345dc2a-ffcb-49e6-8e58-a7f741ee5421.PNG">

The same IDs are used for all EepkTypes throughout the game files (defined in vfx_spec.ers).

**Comment by LazyBone152** [comment]
I remember an issue with the game where some skill IDs would use a different EepkType than the actual type of the skill. Happened with Awokens, so this is probably just that.

**Comment by Erichsen-Xero** [comment]
> I remember an issue with the game where some skill IDs would use a different EepkType than the actual type of the skill. Happened with Awokens, so this is probably just that.

I see, so from what I gather this is an issue with how the official stuff handles some declarations for Skill EepkType for BSAs, and hence can't be fixed?

**Comment by LazyBone152** [comment]
I believe so. You can test it by using other IDs for the skill and seeing what EepkType it needs.
