### ISSUE TITLE
ACE can add new adx file types but wont let you select ADX for file

### ISSUE THREAD

**Issue by DeathChaos25** [LazyBone152/XV2-Tools#24]
While ACE works perfectly for games that use ADX audio, while it can add new ADX CUE IDs to the ACB, it will not allow you to select an ADX sound when adding it, meaning you need to use wav or hca, which is rather strange, I'd like to be able to select existing ADX audio files when adding a new ADX to an acb.

**Comment by LazyBone152** [comment]
Seems to just be a oversight. I have added adx to those menus and released an update for that just now.

**Comment by DeathChaos25** [comment]
Hello, thank you for responding and adding this to ACE.

However, it seems like ADX added through this new method cause errors on ACE, perhaps it tries to re-encode an adx from something else?

Here is the error log produced by ACE
[ace_log.txt](https://github.com/LazyBone152/XV2-Tools/files/7637606/ace_log.txt)
.

**Comment by LazyBone152** [comment]
I'm not sure what the issue there is but it looks like its coming from the VGAudio. All tracks loaded are "converted" even if they are being added as the same encoding type, which is just the way that library works. 

I've added an exception to this handling where if both the input and output are adx, it just returns the original file. Let me know if this fixes the issue.
[ACE.ACE.v0.7.6.0.zip](https://github.com/LazyBone152/XV2-Tools/files/7637632/ACE.ACE.v0.7.6.0.zip)

**Comment by DeathChaos25** [comment]
Yes, this seems to have fixed the issue, no problems now!

**Comment by DeathChaos25** [comment]
Apologies, seems like we missed a tiny problem.

If you try to replace an existing ADX, with another ADX, ACE will change the encoding type of that track to HCA, making it unplayable, and further replacing makes it stay as HCA.

Attached is a sample acb/awb containing 2 adx, as well as an adx track that can be used to see this problem happen.
[Uploading ACE Test.zip…]()

**Comment by LazyBone152** [comment]
Okay... so it appears the EncodeType was actually hardcoded to HCA when replacing.

**Comment by LazyBone152** [comment]
I was able to add adx tracks to your sample without issue after changing that one line. 
[ACE.ACE.v0.7.7.0.zip](https://github.com/LazyBone152/XV2-Tools/files/7637859/ACE.ACE.v0.7.7.0.zip)

**Comment by DeathChaos25** [comment]
Seems to work with no issues now, many thanks!
