### ISSUE TITLE
XV2 XMLiser (Version 2.9) still having issues when working with EANs/ ESKs. 

### ISSUE THREAD

**Issue by Erichsen-Xero** [LazyBone152/XV2-Tools#29]
Basically what the Issue title says. 2.9 just can't seem to reliably serialise EANs and throws errors. 

This certainly seems like a Bug on the tool's end since **Version 2.63 works fine**. 

![Screenshot (3)](https://user-images.githubusercontent.com/93145460/145682617-43ed6bf0-cb1c-4f80-8e6c-b47dc0860c88.png)

**Comment by LazyBone152** [comment]
By the looks of the exception it is trying to run the LinkEskData methods which aren't needed for XML serialization (only required for animation playback/edit).

**Comment by LazyBone152** [comment]
Well that shouldn't actually cause an issue (even if its completely useless for serialization). The problem seems to be when animations don't have any components on them, so it should only actually happen on modded EANs. I'll release a fix for this later.

**Comment by LazyBone152** [comment]
Should be fixed in 3.0.
