### ISSUE TITLE
EEPK Organizer: Circular texture problem for supertextures

### ISSUE THREAD

**Issue by StardustZfighter** [LazyBone152/XV2-Tools#30]
sometime circular textures have only 1 forth of them appear in game. here's an example
![DRAGON BALL XENOVERSE 2 12_18_2021 1_07_24 PM](https://user-images.githubusercontent.com/82039572/146643926-f89b7bc6-51d5-4fde-806a-e689a8d07729.png)
e

**Comment by LazyBone152** [comment]
Fixed in 0.9.4.

Well, "fixed" anyway. These mirrored textures are now just excluded from merging.
