### ISSUE TITLE
ACE SMT V ACB error

### ISSUE THREAD

**Issue by DeathChaos25** [LazyBone152/XV2-Tools#31]
SMT V ACB seem to have some new field (newer format?) that makes ACE error out when opening normally, however the file can be opened and previewed perfectly fine with the Force Open option.

attached are ACB files that give error and the error log from ACE.
[SMTV acb.zip](https://github.com/LazyBone152/XV2-Tools/files/7775354/SMTV.acb.zip)
[ace_log.txt](https://github.com/LazyBone152/XV2-Tools/files/7775356/ace_log.txt)

**Comment by LazyBone152** [comment]
Should now be fully supported in 0.8
