### ISSUE TITLE
ACE VOX/SE issue

### ISSUE THREAD

**Issue by LOLDJ23** [LazyBone152/XV2-Tools#34]
Seems that saving a VOX file corrupts the IDs from 58 to 69, based on what i tested seems that the voice line played on ID 70 is copypasted over all the others 11. 

A similar issue could be the one about DEMO SEs, for example the CAR_D05_10_SE has the last sound (the ID 6) repeated in all the other IDs except on the number 4 (you can also check CAR_D05_17_SE, this time there are 2 sounds repeated). This issue appear without saving or adding anything to the SE.

**Comment by LazyBone152** [comment]
Can you tell me a vanilla game VOX that causes this issue (+ lang)? I tested with a few ACBs and couldn't reproduce it at all.

**Comment by LazyBone152** [comment]
Found the bug. It was an issue with loading multiple AWBs so it only occurred when streaming tracks and internal tracks were used in the same ACB.
