### ISSUE TITLE
Cannot save SMT V ACB files.

### ISSUE THREAD

**Issue by Algo1122** [LazyBone152/XV2-Tools#36]
[Log + ACB.zip](https://github.com/LazyBone152/XV2-Tools/files/7921829/Log.%2B.ACB.zip)

Unfortunately ACE can't save SMT V ACB files, I'm not sure what incurs this as even without editing the file at all the error persists. Sorry, if this is my fault somehow then I'll take the fall for it.

**Comment by LazyBone152** [comment]
Was just a minor oversight. It should now work in 0.8.1.
