### ISSUE TITLE
AudioCueEditor Yakuza 5 fighter voices don't work

### ISSUE THREAD

**Issue by f7cjo** [LazyBone152/XV2-Tools#37]
When trying to open fighter voices from Yakuza 5 Remastered, the tool throws an error:

"cannot get command at index 0 on SynthParameterPallet because it is out of range."
Log file: [ace_log.txt](https://github.com/LazyBone152/XV2-Tools/files/7965537/ace_log.txt)

This doesn't happen with fighter voices from other games on the same engine or a few other acbs from 5 that I tried.
I've attached a few example acbs.

[sound.par.unpack.zip](https://github.com/LazyBone152/XV2-Tools/files/7965543/sound.par.unpack.zip)

**Comment by LazyBone152** [comment]
Looks like an issue with the implementation for ParameterPallet values in the last update. Those ACBs are an older version that don't even have that value and ACE is setting it as the default value (0).

**Comment by LazyBone152** [comment]
Fixed in 0.8.2
