### ISSUE TITLE
AudioCueEditor Drag & dropping acbs/awbs doesn't work

### ISSUE THREAD

**Issue by MikoMMM** [LazyBone152/XV2-Tools#38]
Whenever I try to drag and drop an acb/awb, it shows this error.

![image](https://user-images.githubusercontent.com/33367804/151710279-d940cf1f-fea3-4829-aa5c-fb03598e30ba.png)

It doesn't generate any error in the ACE log by the way.

**Comment by LazyBone152** [comment]
Drag and drop is only implemented for audio files currently (doing so will add a new track).

I'll look into allowing ACB files to be loaded that way in the future.

**Comment by LazyBone152** [comment]
feature added with the load times fix update
