### ISSUE TITLE
LB Mod Installer: BCS Installation gender error

### ISSUE THREAD

**Issue by StardustZfighter** [LazyBone152/XV2-Tools#43]
Whenever trying to install BCS.xml it shows this error. Keep in mind that the BCS in for an X2M Character
![Install Error 1_31_2022 6_56_11 PM](https://user-images.githubusercontent.com/82039572/151821751-718d044f-2ece-403b-8d0f-d0a163dd1759.png)

**Comment by StardustZfighter** [comment]
Update: Apparently it was caused by a minor difference between XML Serializer and the XML Tool in LB Mod Installer

**Comment by LazyBone152** [comment]
Yeah the main serialzier isn't updated yet. This is why XmlTool exists in the first place.
