### ISSUE TITLE
AudioCueEditor: importing non-ACE exported .wavs (format: 3) over .acb tracks results in an error

### ISSUE THREAD

**Issue by MikoMMM** [LazyBone152/XV2-Tools#44]
Whenever I try to import a wav file from Shin Megami Tensei V, this error pops up
![image](https://user-images.githubusercontent.com/33367804/152738320-147b06cc-489d-40d6-9052-2d6f54c681b2.png)
A friend has reported the same issue happening with exported .wavs from Audacity.
It doesn't spawn anything in the ace_log.txt but here's the sample .wav https://drive.google.com/file/d/1zaF4MUDQaqkxN7o8PsDsotMxHJ_iFH2q/view?usp=sharing

**Comment by LazyBone152** [comment]
Try exporting as a signed 16-bit WAV. It seems that float 32-bit WAVs are unsupported by the audio library ACE uses.
