### ISSUE TITLE
Unable to open ACB/AWB file that has unique HCA key.

### ISSUE THREAD

**Issue by Crafty-The-Fox** [LazyBone152/XV2-Tools#47]
I have the HCA key for the file, but i dont know how to use it. I cant find a box to put the HCA key in, or even a txt file. If there is a way to use the HCA key with this program, please let me know

**Comment by LazyBone152** [comment]
Got a sample to share of an encrypted ACB that wont open?

**Comment by Crafty-The-Fox** [comment]
Sorry for the late response, but i can get you one tomorrow.

**Comment by Crafty-The-Fox** [comment]
> Got a sample to share of an encrypted ACB that wont open?

[broken acb and awb.zip](https://github.com/LazyBone152/XV2-Tools/files/8258061/broken.acb.and.awb.zip)

here you go, i can provide the key if you need it but the key should be on that page.

**Comment by Crafty-The-Fox** [comment]
slight bump

**Comment by LazyBone152** [comment]
Adding in all the encryption keys from vgmstream seems to have done the trick 

But before I do another release I want to get the encryption stuff from issue #42 done.

**Comment by Crafty-The-Fox** [comment]
> Adding in all the encryption keys from vgmstream seems to have done the trick 
> 
> 
> 
> But before I do another release I want to get the encryption stuff from issue #42 done.

alright, thank you!

**Comment by F121Live** [comment]
Feels amazing to hear news about issue #42  , thank you very much!

**Comment by LazyBone152** [comment]
Encryption keys were added back in 0.9.
