### ISSUE TITLE
Unable to add audio to the awb instead of the acb file.

### ISSUE THREAD

**Issue by Crafty-The-Fox** [LazyBone152/XV2-Tools#48]
When trying to edit a awb file, i open the ACB file in ACE, import new songs and it saves them to the acb it looks like, because it goes from 36kb to 3mb. is there a way to inject it into the AWB file instead? (note the awb file is like 1.1 gigs)

**Comment by Crafty-The-Fox** [comment]
also, ACE doesn't seem to support files bigger than 2gb?

**Comment by LazyBone152** [comment]
You need to set the tracks as streaming for them to go into the external AWB.

There is an option for this when first adding them, but it can also be changed afterwards in the waveform section after selecting a track (on right side).
