### ISSUE TITLE
ACE v0.9.0 broke ADX compatibility

### ISSUE THREAD

**Issue by DeathChaos25** [LazyBone152/XV2-Tools#57]
As title says, it is no longer possible to open acb/awb files containing ADX sound files, ACE gives an error saying "not a valid HCA file" and then refuses to open the acb/awb file.

[ace_log.txt](https://github.com/LazyBone152/XV2-Tools/files/9427118/ace_log.txt)

**Comment by LazyBone152** [comment]
Should be fixed in 0.9.1.
