### ISSUE TITLE
AudioCueEditor issue with JJBA:ASBR v_charasel.acb

### ISSUE THREAD

**Issue by 80constant** [LazyBone152/XV2-Tools#58]
When opening the file there are duplicates of an unwanted sound (Dio Brando's first select quote, the first track in the archive) in all of the cues, adding 2 more to the should be 2 total sounds per cue.
After saving and testing in game, all of the new character cues added to the R release go silent, and Will Zeppeli's (1zpl) cue get's shared with Jonathan Joestar's (1jnt) cue.

Here are the two [files.](https://cdn.discordapp.com/attachments/651051460318068746/1017837342934962286/v_charasel.zip)

**Comment by LazyBone152** [comment]
I see whats wrong here.

This ACB has some dummy values that ACE is seeing as additional tracks, and so is adding track 0 to those cues. 

This shouldn't be difficult to fix, but it does make me wonder what will happen if those dummy values aren't there. Hopefully it just works normally.

**Comment by LazyBone152** [comment]
[ACE Test.zip](https://github.com/LazyBone152/XV2-Tools/files/9541890/ACE.Test.zip)
This version reads the tracks correctly, but on save it wont add those dummy values.

If there's still trouble with the tracks being silent then I can try to add them when saving, but if its not needed then I'll just leave it as is.

**Comment by 80constant** [comment]
The extra tracks are indeed gone, however every cue after the "V_charasel_8jsk01_02" cue are still silent in game, unfortunately.
Thank you for the support, I really appreciate it.

**Comment by LazyBone152** [comment]
[ACE Test2.zip](https://github.com/LazyBone152/XV2-Tools/files/9542008/ACE.Test2.zip)
Any difference with this build?

**Comment by 80constant** [comment]
Unfortunately, no difference, still silent in game.

**Comment by LazyBone152** [comment]
[ACE Test3.zip](https://github.com/LazyBone152/XV2-Tools/files/9542072/ACE.Test3.zip)
Well then, I guess its time to try adding those extra values in. I didn't think they mattered but there's nothing else to try right now. I can't see any other issue with the acb.

**Comment by 80constant** [comment]
Still does not seem to work, would the file size bump on the .acb have anything to do with it? 
More or less I'm just kind of curious about it, since it goes from 24kb to 37kb after a save with no changes.
Again, I super appreciate the support.

**Comment by LazyBone152** [comment]
[v_charasel.zip](https://github.com/LazyBone152/XV2-Tools/files/9639260/v_charasel.zip)

Actually, that might just be it. I've noticed that your ACB lacks some data that ACE always automatically regenerates, so when its saving it creates this data. Which might just explain the silencing.

In the ACB posted above I've removed this data through manual editing, after having saved it with ACE. Let me know if it still has the issue.

**Comment by 80constant** [comment]
Yup, that seem to have done the trick! The characters after 8jsk are no longer silent.

**Comment by LazyBone152** [comment]
Ah nice. I thought that might do the trick.

Now just to be sure before I close this issue, does this build work correctly? 
[ACE Test.zip](https://github.com/LazyBone152/XV2-Tools/files/9639339/ACE.Test.zip)

**Comment by 80constant** [comment]
Ah, I really apologize, I'm pretty sure I imported the wrong file when trying to test the files you gave me, it's still silent..

If there's nothing that can be done at this point I'm okay with giving a shot at trying to take apart the the AWB manually and reassemble it filling in the spaces for the HCAs.

**Comment by LazyBone152** [comment]
Well that is unfortunate.

But I did notice two more slight differences between the original and saved ACB which are worth testing I think. I've edited them back to the original state in this saved ACB.
[v_charasel.zip](https://github.com/LazyBone152/XV2-Tools/files/9639428/v_charasel.zip)

**Comment by 80constant** [comment]
Still no luck..

**Comment by LazyBone152** [comment]
Alright... well there is one last thing to try. It's kind of stupid, but it does line up with what you've told me about what cues are being made silent.

Basically the cue names in ACE are always saved sequentially, but in some ACBs (such as yours) they appear out of order. The cue “V_charasel_8jsk01_02” is where the difference starts, which is the cue you say is the first silent one.

[v_charasel.zip](https://github.com/LazyBone152/XV2-Tools/files/9639686/v_charasel.zip)

**Comment by 80constant** [comment]
Alright, I made sure to double check I was importing the right things this time, and yes! It does work, nothing is silent.

**Comment by LazyBone152** [comment]
That's good to hear. I've updated ACE to now properly preserve the original name order, as long as no cues get deleted.

Give it a try and see if it works as well.

[ACE Test.zip](https://github.com/LazyBone152/XV2-Tools/files/9639803/ACE.Test.zip)

**Comment by 80constant** [comment]
https://user-images.githubusercontent.com/92841790/192167518-1113642f-3803-49f5-aba5-2a947c3d03ef.mp4

It works perfectly! Thank you so much for the help, once again.
