### ISSUE TITLE
AudioCueEditor Feature Report: More loop unit options

### ISSUE THREAD

**Issue by MikoMMM** [LazyBone152/XV2-Tools#59]
To explain: An option or toggle to edit loops in hh:mm:ss:ms like in Eternity Audio Tools would be nice, instead of just samples, like this:
![151718773-226c113f-70b4-4643-a757-e687f6152c8c](https://user-images.githubusercontent.com/33367804/192832659-8999af75-6ea9-48c6-bb2d-f1b832e93bd1.png)

**Comment by LazyBone152** [comment]
Implemented in 1.0
