### ISSUE TITLE
XV2 Xml Serializer 3.8.0 still corrupting .emds

### ISSUE THREAD

**Issue by LOLDJ23** [LazyBone152/XV2-Tools#64]
The only issue i'm able to report is based on Goku SSJ3 face where it gets corrupted when using Serializer. No need to do anything into the .emd, the issue should appear when dragging and dropping back onto Serializer.
![image](https://user-images.githubusercontent.com/88945466/207558562-b7667d66-432e-4da3-ada3-14e329a07684.png)
![image2](https://user-images.githubusercontent.com/88945466/207558575-81e81d16-d6d0-4c58-8b90-b19839722d37.png)

**Comment by LazyBone152** [comment]
Does this still happen with the latest build?

**Comment by LazyBone152** [comment]
I couldn't replicate this issue with the vanilla Goku SS3 face (GOK_005_Face_base.emd), even with using an older version of the serializer.

Can you post the EMDs here (before and after) as well as the XML?

**Comment by LOLDJ23** [comment]
Git doesn't support EMDs so gonna use my Drive:
https://drive.google.com/drive/folders/19gOMYqpjxBJInOZFixYikHoix6asC12e?usp=sharing

As i said above the issue still the same:
Get GOK_005_Face_base.emd.
Use XV2 Xml Serializer (3.10.0) (the normal version, not x64. idk if something changes).
Turn back the XML into EMD.
issue replicated.

**Comment by LazyBone152** [comment]
<img width="529" alt="Capture" src="https://github.com/LazyBone152/XV2-Tools/assets/60512194/9d676fbf-a8c4-40b5-bacb-6b6a931777cc">

The EMD you have marked as "CORRUPTED" works perfectly in game, XenoKit and Xenoviewer, when paired with the vanilla embs and emms, so I'm not sure whats going on here. I also tested the other one just in case they were mislabeled and got the same result.

**Comment by LazyBone152** [comment]
Actually, I now see it does break when applied to a skeleton in Xenoviewer, though that doesn't explain how it still works ingame and XenoKit

**Comment by LOLDJ23** [comment]
Yes, the face does break when attached to its skeleton in Xenoviewer and also in Blender but doesn't ingame. If we only need to see the results ingame then it's not a big deal but if we want to create a face animation using Blender then it might be a lil difficult since half of the face is corrupted. In any case serializer corrupts it. Same issue can be seen on the Rist of Goku SSJ4 (right hand).

**Comment by LazyBone152** [comment]
It's not really a corruption since all the data is there and works normally in the actual game, more like an incompatibility with some other tools.

But anyway, its now fixed in the latest release (3.11). Any old "corrupted" EMDs should also be fixed by running them through the updated version.
