### ISSUE TITLE
Where can I find the xml serializer?

### ISSUE THREAD

**Issue by Ironwally** [LazyBone152/XV2-Tools#7]
Hey,

sorry for asking this, but I just can't find anything...

If I want to use the xml serializer, do I have to download and run the whole project in Visual Studios or is there an "xml Serializer.exe" somewhere?

To try making my own ".exe" I downloaded the whole project and opened it in Visual Studios.
Now here comes my problem:

when trying to start xml serializer within visual studios it gives me the following error message:

As it is stated here: "FodyIsolated.dll or an instance (Abhängigkeit) of it was not found."
Please, I hope you can help me, I really tried everything.

Erstellen gestartet...
1>------ Erstellen gestartet: Projekt: Xv2CoreLib, Konfiguration: Debug Any CPU ------
1>MSBUILD : error : Fody: An unhandled exception occurred:
1>MSBUILD : error : Exception:
1>MSBUILD : error : Die Datei oder Assembly "file:///D:\Games\Mods\Xenoverse 2 mods\XV2-Tools-master\XV2-Tools-master\packages\Fody.3.3.2\netclassictask\FodyIsolated.dll" oder eine Abhängigkeit davon wurde nicht gefunden. Der Vorgang wird nicht unterstützt. (Ausnahme von HRESULT: 0x80131515)
1>MSBUILD : error : Type:
1>MSBUILD : error : System.IO.FileLoadException
1>MSBUILD : error : StackTrace:
1>MSBUILD : error :    bei System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
1>MSBUILD : error :    bei System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
1>MSBUILD : error :    bei System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
1>MSBUILD : error :    bei System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
1>MSBUILD : error :    bei System.Reflection.Assembly.LoadFrom(String assemblyFile, Evidence securityEvidence)
1>MSBUILD : error :    bei System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)
1>MSBUILD : error :    bei System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName)
1>MSBUILD : error :    bei System.AppDomain.CreateInstanceFromAndUnwrap(String assemblyName, String typeName)
1>MSBUILD : error :    bei System.AppDomain.CreateInstanceFromAndUnwrap(String assemblyName, String typeName)
1>MSBUILD : error :    bei Processor.ExecuteInOwnAssemblyLoadContext() in C:\projects\fody\Fody\Processor.cs:Zeile 143.
1>MSBUILD : error :    bei Processor.Inner() in C:\projects\fody\Fody\Processor.cs:Zeile 103.
1>MSBUILD : error :    bei Processor.Execute() in C:\projects\fody\Fody\Processor.cs:Zeile 51.
1>MSBUILD : error : Source:
1>MSBUILD : error : mscorlib
1>MSBUILD : error : TargetSite:
1>MSBUILD : error : System.Reflection.RuntimeAssembly _nLoad(System.Reflection.AssemblyName, System.String, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean)
1>MSBUILD : error : Es wurde versucht, eine Assembly von einer Netzwerkadresse zu laden, was in früheren Versionen von .NET Framework zum Ausführen der Assembly als Sandkastenassembly geführt hätte. In dieser Version von .NET Framework wird die CAS-Richtlinie standardmäßig nicht aktiviert, dieser Ladevorgang kann daher gefährlich sein. Wenn Sie nicht beabsichtigen, durch diesen Ladevorgang eine Sandkastenassembly zu erstellen, aktivieren Sie den loadFromRemoteSources-Schalter. Weitere Informationen finden Sie unter "http://go.microsoft.com/fwlink/?LinkId=155569".
1>MSBUILD : error : Type:
1>MSBUILD : error : System.NotSupportedException
1>MSBUILD : error : StackTrace:
1>MSBUILD : error : 
1>MSBUILD : error : 
2>------ Erstellen gestartet: Projekt: XV2 Xml Serializer, Konfiguration: Debug Any CPU ------
2>CSC : error CS0006: Metadatendatei "D:\Games\Mods\Xenoverse 2 mods\XV2-Tools-master\XV2-Tools-master\Xv2CoreLib\bin\Debug\Xv2CoreLib.dll" wurde nicht gefunden.
========== Erstellen: 0 erfolgreich, 2 fehlerhaft, 0 aktuell, 0 übersprungen ==========

Still thanks for the great work!
Hope hearing from you soon
Ironwally

**Comment by LazyBone152** [comment]
The compiled tools are hosted: [here](https://animegamemods.freeforums.net/thread/3139/tools-lazybone)

Currently only the code is hosted on github.

**Comment by Ironwally** [comment]
Ahhh thank you soo much!
Keep up the great work!
