### ISSUE TITLE
EEPK Organizer : EMO asset tab operations mess up EEPK registries, the tool fails to load EMO asset-edited EEPKs.

### ISSUE THREAD

**Issue by Erichsen-Xero** [LazyBone152/XV2-Tools#72]
Duplicating EMOs, deleting EMO textures, et cetera - I have begun encountering EEPK load fails when doing practically anything with EMO assets within the 2.0.2 organizer. Seemingly it botches the EEPK registries themselves owing to some failure at saving the EMO operations properly.

**Comment by LazyBone152** [comment]
This should be fixed in 2.0.3, at least as far as duplicate and paste goes. Let me know if it happens on any other type of edit.
