### ISSUE TITLE
I can't open .acb file

### ISSUE THREAD

**Issue by random-137** [LazyBone152/XV2-Tools#8]
Hi,i tried to using ACE tool to edit this .acb file but have no luck,any chance you could take a look at it?

https://www.mediafire.com/file/2yvrht9ww6yby2d/bgm.zip/file

**Comment by LazyBone152** [comment]
The awb file is missing. Do you have it?

**Comment by random-137** [comment]
yes,i have it here 
https://www.mediafire.com/file/kuziv046z5c2pj8/bgm.awb/file

**Comment by random-137** [comment]
i don't know if it will help but i also found an acf file
[bgm.acf.zip](https://github.com/LazyBone152/XV2-Tools/files/5977633/bgm.acf.zip)

**Comment by LazyBone152** [comment]
Sorry for the long delay, just been busy with other stuff. 

That ACB appears to be a slightly earlier version of the format than what ACE was originally made for, but it shouldn't be hard to support it.

**Comment by LazyBone152** [comment]
Issue should now be fixed in 0.7.

**Comment by random-137** [comment]
i tried version 0.7 and it does read it now,but when i add new cue and put an hca track in,it give me this error
[ace_log.txt](https://github.com/LazyBone152/XV2-Tools/files/6204007/ace_log.txt)

**Comment by LazyBone152** [comment]
Ah there were a few issues with loops in that release it seems. Can you retest with 0.71?

**Comment by random-137** [comment]
alright, i tested with 0.71 and yes it can save now but it seem the game doesn't read the bgm awb file but it reading other awb (which contain voice lines instead),the game i'm trying to change bgm is naruto storm revolution in case you want to test it yourself

**Comment by LazyBone152** [comment]
That's very odd... I did notice something wrong that _might_ cause that, but I'm not sure. Give this build a try:
[ACE.zip](https://github.com/LazyBone152/XV2-Tools/files/6207187/ACE.zip)

**Comment by random-137** [comment]
yes,it is working now,you even fixed the game crash when i try to add a "Sequence" cue,although there 1 more small bug is that the title_mode cue that have 2 track is get mixed together somehow https://youtu.be/R3B5KkdGbwc

**Comment by LazyBone152** [comment]
So it was just because of a dumb oversight on my behalf rather than a major issue... good to hear.

This build may fix that remaining bug. Just a typo, but it caused a whole set of data to be not loaded on synth-type cues.
[ACE.zip](https://github.com/LazyBone152/XV2-Tools/files/6210684/ACE.zip)

**Comment by random-137** [comment]
everything is work perfect now,thank you very much again for this awesome tool :D
